services:
  - type: web
    name: ludo-backend
    env: node
    buildCommand: cd Ludo/Ludo/ludo-contest-server && npm install
    startCommand: cd Ludo/Ludo/ludo-contest-server && node app.js
    rootDirectory: Ludo/Ludo/ludo-contest-server
    envVars:
      - key: MONGODB_URI
        value: "mongodb+srv://d7549377:ywTi7C6vOCSVOdtk@cluster0.tmgl7.mongodb.net/Ludo"
      - key: JWT_SECRET
        value: "ownafgikabdfnaogahrd"
      - key: PORT
        value: "10000"

  - type: web
    name: ludo-frontend
    env: static
    buildCommand: cd ludo-contest-frontend && npm install && npm run build
    staticPublishPath: ./ludo-contest-frontend/build
